# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CBW GitHub
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  CBW focuses on training researchers to use the latest approaches in computational biology to deal with large datasets.
plugins:
  - jekyll-sitemap
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bioinformaticsdotca.github.io" # the base hostname & protocol for your site
twitter_username: Bioinfodotca
github_username: bioinformatics-ca

# Build settings
#markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Google Services
google_analytics: UA-90204097-1
